<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BT1704430" failures="1" tests="3" name="TestRunner.CucumberTestRunner" time="9.072" errors="0" timestamp="2025-09-06T21:23:28 IST" skipped="0">
  <testcase classname="TestRunner.CucumberTestRunner" name="runScenario" time="3.656"/>
  <testcase classname="TestRunner.CucumberTestRunner" name="runScenario" time="3.510"/>
  <testcase classname="TestRunner.CucumberTestRunner" name="runScenario" time="1.906">
    <failure message="expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/v1/inventory.html] but found [https://www.saucedemo.com/v1/]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinations.LoginStepsDefination.user_is_navigated_to_home_page(LoginStepsDefination.java:42)
at âœ½.user is navigated to Home page(file:///C:/Users/KIIT/eclipse-workspace-Practice/AutomationProject/CucumberJenkins/src/test/resources/features/login.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestRunner.CucumberTestRunner -->
